# Permite importaciones absolutas
from .hogar import Hogar
from .rol import Rol
from .modulo import Modulo
from .permiso import Permiso
from .miembro import Miembro
from .tarea import Tarea
from .mensaje import Mensaje
from .evento import Evento